image: maven:3.3.9-jdk-8

variables:
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

deploy:
  stage: deploy
  script:
    - mvn $MAVEN_CLI_OPTS clean test deploy
#  only:
    ##    - master